version: '3.9'

services:
  db:
    container_name: Lunch-Postgres
    image: postgres:12.18
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Lunch123
    volumes:
      - lunch-data:/var/lib/postgresql/data

volumes:
  lunch-data: